services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
