services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_ID=${GOOGLE_ID}
      - MONGODB_ID=${MONGODB_ID}

  frontend:
    build:
      context: ./Frontend
      args:
        VITE_GOOGLE_ID: ${VITE_GOOGLE_ID}
        VITE_HUGGINGFACE_ID: ${VITE_HUGGINGFACE_ID}
    ports:
      - "80:80"
    depends_on:
      - backend
